name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Create ESLint config dynamically
        run: |
          echo "import { flatConfig } from '@eslint/eslintrc';

          export default [
            {
              languageOptions: {
                globals: {
                  browser: true,
                  es2021: true,
                },
                parser: '@babel/eslint-parser',
                parserOptions: {
                  ecmaVersion: 12,
                  sourceType: 'module',
                },
              },
              rules: {
                semi: ['error', 'always'],
                quotes: ['error', 'single'],
              },
            },
          ];" > eslint.config.mjs  # Use the .mjs extension for ES module

      - name: Run lint
        run: yarn eslint .
