name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js version 20
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies using yarn
      - name: Install dependencies
        run: yarn install

      # Step 4: Create a temporary ESLint configuration file
      - name: Create temporary ESLint config
        run: |
          echo "export default [{ files: ['**/*.js'], languageOptions: { sourceType: 'module' }, rules: {} }];" > eslint.config.js
      # Step 5: Run lint using the temporary ESLint config
      - name: Run lint
        run: yarn eslint .

      # Step 6: Remove the temporary ESLint configuration
      - name: Cleanup ESLint config
        run: rm eslint.config.js